version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - '5438:5432'